// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlameniciAplikacija.Data;

#nullable disable

namespace PlameniciAplikacija.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420204430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DjelatnikProject", b =>
                {
                    b.Property<int>("DjelatniciId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjektiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DjelatniciId", "ProjektiId");

                    b.HasIndex("ProjektiId");

                    b.ToTable("DjelatnikProject");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Djelatnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RadnoMjesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Djelatnici");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.FazaProjekta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPlaniranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlaniraniPocetak")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlaniraniZavrsetak")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Redosljed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StvarniPocetak")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StvarniZavrsetak")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("FazeProjekta");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Kupac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KontaktOsoba")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kupci");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Napomena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioritet")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Napomene");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojProjekta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumUnosa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KupacId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NapomenaPrioritet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OcekivaniRokIsporuke")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Prioritet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RealniRokIsporuke")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusLansiranja")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusPripremeRada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusProizvodnje")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KupacId");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.RadniNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumOtvaranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumZatvaranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OznakaNaloga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.ToTable("RadniNalozi");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.StavkaProizvodnje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumPlaniranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjektId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RadniNalogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("RadniNalogId");

                    b.ToTable("StavkeProizvodnje");
                });

            modelBuilder.Entity("DjelatnikProject", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Djelatnik", null)
                        .WithMany()
                        .HasForeignKey("DjelatniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlameniciAplikacija.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjektiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.FazaProjekta", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Project", "Projekt")
                        .WithMany("FazeProjekta")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Napomena", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Djelatnik", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlameniciAplikacija.Models.Project", null)
                        .WithMany("Napomene")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Project", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Kupac", "Kupac")
                        .WithMany("Projekti")
                        .HasForeignKey("KupacId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kupac");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.RadniNalog", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Project", "Projekt")
                        .WithMany("RadniNalozi")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.StavkaProizvodnje", b =>
                {
                    b.HasOne("PlameniciAplikacija.Models.Project", "Projekt")
                        .WithMany("StavkeProizvodnje")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlameniciAplikacija.Models.RadniNalog", "RadniNalog")
                        .WithMany("Operacije")
                        .HasForeignKey("RadniNalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Projekt");

                    b.Navigation("RadniNalog");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Kupac", b =>
                {
                    b.Navigation("Projekti");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.Project", b =>
                {
                    b.Navigation("FazeProjekta");

                    b.Navigation("Napomene");

                    b.Navigation("RadniNalozi");

                    b.Navigation("StavkeProizvodnje");
                });

            modelBuilder.Entity("PlameniciAplikacija.Models.RadniNalog", b =>
                {
                    b.Navigation("Operacije");
                });
#pragma warning restore 612, 618
        }
    }
}
